server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zen?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 59.110.93.61
    port: 6379
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hbnu.zen.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: "zen-project-jwt-secret-key-32-bytes!!"
    expire-minutes: 480
  reservation:
    lock-wait-ms: 800
    lock-lease-ms: 5000
  lecture:
    lock-wait-ms: 800
    lock-lease-ms: 5000
  equipment:
    lock-wait-ms: 800
    lock-lease-ms: 5000
  bus:
    lock-wait-ms: 800
    lock-lease-ms: 5000
